### ISSUE TITLE
PROBLEM WITH SIMPLEDATEFORMAT

### ISSUE THREAD

**Issue by Migatuno** [EMBEDONIX/AndroidNoteTaker#1]
Hello.
First of all, congratulations for your tutorials and code. 
I am starting in this world of coding, and it is really a whole new world.
Second, I have a problem with SimpleDateFormat. Android Studio says that it doesn´t target API 15.
Only 24 and more. I did an annotation target  to this method and built te APK but it doesn´t work, it closes after saving a note.
Any help?
Again, thank you,
David López.

**Comment by SaeidYazdani** [comment]
It's strange, SimpleDateFormat is valid since API1 I think! do you have appcompat package installed in the SDK?

**Comment by Migatuno** [comment]
Hello!
Thanks for answering.
I will check It. I'm travelling now but I will tell you ASAP.
Thanks again.

**Comment by Migatuno** [comment]
That was the problem! I updated, downloaded and restart Android Studio and changed the build grade file to adjust to the new configuration. Now the problem is gone.
Thank you very much.
